dist: trusty
sudo: false

language: elixir
otp_release:
  - 19.3
elixir:
  - 1.4.2

cache:
  directories:
    - _build
    - deps

addons:
  postgresql: "9.6"

install:
  - cp test/support/dummy/config/config.secret.sample.exs test/support/dummy/config/config.secret.exs
  - mix local.hex --force
  - mix local.rebar --force
  - mix do deps.get, compile
before_script:
  - mix db.reset
script:
  - mix test
